//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CooperVisionAPIPF.ModeloBD
{
    using global::System;
    using global::System.Data.Entity;
    using global::System.Data.Entity.Infrastructure;
    
    public partial class AccessRequestsEntities : DbContext
    {
        public AccessRequestsEntities()
            : base("name=AccessRequestsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access> Accesses { get; set; }
        public virtual DbSet<Approver> Approvers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Headquarter> Headquarters { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Supervisor> Supervisors { get; set; }
        public virtual DbSet<System> Systems { get; set; }
        public virtual DbSet<AccessPosition> AccessPositions { get; set; }
        public virtual DbSet<AccessRequested> AccessRequesteds { get; set; }
    }
}
