//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CooperVisionAPIPF.ModeloBD
{
    using global::System;
    using global::System.Collections.Generic;
    
    public partial class System
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System()
        {
            this.Accesses = new HashSet<Access>();
        }
    
        public long ID { get; set; }
        public string System1 { get; set; }
    
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Access> Accesses { get; set; }

        public struct DateTime
        {
        }
    }
}
